FROM centos

RUN \
	yum install -y http://mirrors.sohu.com/fedora-epel/beta/7/x86_64/epel-release-7-0.2.noarch.rpm \
	yum install -y nginx \
	yum update -y \ 
	yum upgrade -y \

ADD nginx.conf /etc/nginx/nginx.conf

CMD ["nginx"]

EXPOSE 80 443
